/* ----------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------
Create Sequences
-------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------*/
CREATE SEQUENCE SQ_CM_USR START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE SQ_CM_STOR START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE SQ_CR_USR_STOR START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE SQ_CM_GOOS START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE SQ_CH_VISIT START WITH 1 INCREMENT BY 1 NOCYCLE;
CREATE SEQUENCE SQ_CM_NATI_CD START WITH 1 INCREMENT BY 1 NOCYCLE;

/*
DROP SEQUENCE SQ_CM_USR;
DROP SEQUENCE SQ_CM_STOR;
DROP SEQUENCE SQ_CR_USR_STOR;
DROP SEQUENCE SQ_CM_GOOS;
DROP SEQUENCE SQ_CH_VISIT;
DROP SEQUENCE SQ_CM_NATI_CD;

DROP TABLE CM_USR;
DROP TABLE CM_STOR;
DROP TABLE CR_USR_STOR;
DROP TABLE CM_GOOS;
DROP TABLE CH_VISIT;
DROP TABLE CM_NATI_CD;
*/

/* ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
Create Tables
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ */
CREATE TABLE CM_USR COMMENT '사용자관리'
(
	CM_USR_SEQ bigint NOT NULL COMMENT '순번 : 고유 식별 값' UNIQUE,
	USR_ID varchar(64) NOT NULL COMMENT '사용자아이디 : 사용자 아이디, 전화번호를 아이디로 사용' UNIQUE,
	USR_TP varchar(1) DEFAULT '''U''' NOT NULL COMMENT '사용자구분 : U - 사용자, S - 경영주',
	PASSWD varchar(512) NOT NULL COMMENT 'PASSWD : 비밀번호',
	USR_NM varchar(128) NOT NULL COMMENT '사용자명',
	EMAIL varchar(128) COMMENT '이메일주소',
	NATI_CD varchar(3) COMMENT '국적코드 : 국적코드',	
	MARKET_AGREE_YN varchar(1) DEFAULT '''N''' NOT NULL COMMENT '마케팅동의여부 : 마케팅 동의 여부, Y / N',
	JOIN_YN varchar(1) DEFAULT '''Y''' NOT NULL COMMENT '가입여부',
	PASSWD_CHNG_TOKEN varchar(512) COMMENT '비밀번호 변경 토큰',
	RMKS varchar(512) COMMENT '비고 : 비고',
	REG_PGM_ID varchar(256) NOT NULL COMMENT '등록프로그램아이디',
	REG_USR_ID varchar(50) COMMENT '등록사용자아이디',
	REG_USR_IP varchar(64) NOT NULL COMMENT '등록사용자아이피',
	REG_DTTM datetime NOT NULL COMMENT '등록일시',
	UPD_PGM_ID varchar(256) NOT NULL COMMENT '수정프로그램아이디',
	UPD_USR_ID varchar(50) COMMENT '수정사용자아이디',
	UPD_USR_IP varchar(64) NOT NULL COMMENT '수정사용자아이피',
	UPD_DTTM datetime NOT NULL COMMENT '수정일시',
	PRIMARY KEY (CM_USR_SEQ)
);

CREATE TABLE CM_STOR COMMENT '점포관리'
(
	CM_STOR_SEQ bigint NOT NULL COMMENT '순번 : 고유 식별 값' UNIQUE,
	STOR_ID varchar(64) NOT NULL COMMENT '점포아이디 : 점포 아이디, 매장 전화번호를 아이디로 사용' UNIQUE,
	STOR_NM varchar(128) NOT NULL COMMENT '점포명 : 점포명',
	TEL_NO varchar(32) COMMENT '전화번호 : 매장전화번호',
	NATI_CD varchar(3) COMMENT '국적코드 : 국적코드',	
	ADDR_PT1 varchar(256) COMMENT '주소1 : 주소1',
	ADDR_PT2 varchar(256) COMMENT '주소2 : 주소2',
	ADDR_DTL varchar(256) COMMENT '상세 주소 : 상세 주소',
	ZIP_CD varchar(20) COMMENT '우편번호코드 : 우편번호 코드',	
	SAV_TP varchar(1) DEFAULT '''C''' NOT NULL COMMENT '적립구분 : 적립 구분, C : 쿠폰, P : 포인트',
	SAV_AMT bigint DEFAULT 0 COMMENT '적립량 : 적립량',
	SAV_LIMIT_AMT bigint DEFAULT 0 COMMENT '적립제한량 : 적립제한량',
	USE_AMT bigint DEFAULT 0 COMMENT '사용량 : 사용량( 해당 점포에서 고객이 사용한 양 - 집계 )',
	MAP_LAT varchar(20) COMMENT '지도에 표시할 위도 정보',
	MAP_LNG varchar(20) COMMENT '지도에 표시할 경도 정보',
	RMKS varchar(512) COMMENT '비고 : 비고',
	REG_PGM_ID varchar(256) NOT NULL COMMENT '등록프로그램아이디',
	REG_USR_ID varchar(50) COMMENT '등록사용자아이디',
	REG_USR_IP varchar(64) NOT NULL COMMENT '등록사용자아이피',
	REG_DTTM datetime NOT NULL COMMENT '등록일시',
	UPD_PGM_ID varchar(256) NOT NULL COMMENT '수정프로그램아이디',
	UPD_USR_ID varchar(50) COMMENT '수정사용자아이디',
	UPD_USR_IP varchar(64) NOT NULL COMMENT '수정사용자아이피',
	UPD_DTTM datetime NOT NULL COMMENT '수정일시',
	PRIMARY KEY (CM_STOR_SEQ)
);

CREATE TABLE CR_USR_STOR COMMENT '사용자점포연결'
(
	CR_USR_STOR_SEQ bigint NOT NULL COMMENT '순번 : 고유 식별 값' UNIQUE,
	CM_USR_SEQ bigint NOT NULL COMMENT '사용자관리순번',
	CM_STOR_SEQ bigint NOT NULL COMMENT '점포관리순번',
	SAV_AMT bigint COMMENT '적립량 : 적립량',
	USE_AMT bigint COMMENT '사용량 : 사용량( 해당 점포에서 고객이 사용한 양 - 집계 )',
	ACCUM_AMT bigint DEFAULT 0 COMMENT '누적량 : 누적 사용 및 적립량( 증감 값 )',
	RMKS varchar(512) COMMENT '비고 : 비고',
	REG_PGM_ID varchar(256) NOT NULL COMMENT '등록프로그램아이디',
	REG_USR_ID varchar(50) COMMENT '등록사용자아이디',
	REG_USR_IP varchar(64) NOT NULL COMMENT '등록사용자아이피',
	REG_DTTM datetime NOT NULL COMMENT '등록일시',
	UPD_PGM_ID varchar(256) NOT NULL COMMENT '수정프로그램아이디',
	UPD_USR_ID varchar(50) COMMENT '수정사용자아이디',
	UPD_USR_IP varchar(64) NOT NULL COMMENT '수정사용자아이피',
	UPD_DTTM datetime NOT NULL COMMENT '수정일시',
	PRIMARY KEY (CR_USR_STOR_SEQ)
);

CREATE TABLE CM_GOOS COMMENT '상품관리'
(
	CM_GOOS_SEQ bigint NOT NULL COMMENT '순번 : 고유 식별 값' UNIQUE,
	CM_STOR_SEQ bigint NOT NULL COMMENT '점포관리순번',
	GOOS_NM varchar(512) NOT NULL COMMENT '상품명 : 상품 명',
	SAV_AMT bigint NOT NULL COMMENT '적립량 : 적립량',	
	RMKS varchar(512) COMMENT '비고 : 비고',
	REG_PGM_ID varchar(256) NOT NULL COMMENT '등록프로그램아이디',
	REG_USR_ID varchar(50) COMMENT '등록사용자아이디',
	REG_USR_IP varchar(64) NOT NULL COMMENT '등록사용자아이피',
	REG_DTTM datetime NOT NULL COMMENT '등록일시',
	UPD_PGM_ID varchar(256) NOT NULL COMMENT '수정프로그램아이디',
	UPD_USR_ID varchar(50) COMMENT '수정사용자아이디',
	UPD_USR_IP varchar(64) NOT NULL COMMENT '수정사용자아이피',
	UPD_DTTM datetime NOT NULL COMMENT '수정일시',
	PRIMARY KEY (CM_GOOS_SEQ),
	CONSTRAINT UK_GOOS_STOR_ID_GOOS_NM UNIQUE (CM_STOR_SEQ, GOOS_NM)
);


CREATE TABLE CH_VISIT  COMMENT '방문이력'
(
	CH_VISIT_SEQ bigint NOT NULL COMMENT '순번 : 고유 식별 값' UNIQUE,
	CM_USR_SEQ bigint NOT NULL COMMENT '사용자관리순번',
	CM_STOR_SEQ bigint NOT NULL COMMENT '점포관리순번',
	VISIT_DTM varchar(14) NOT NULL COMMENT '방문일시 : 방문일시 - 14자리, 년(4)+월(2)+일(2)+시(2)+분(2)+초(2)',
	USE_TP varchar(1) NOT NULL COMMENT '사용구분 : 사용 구분, S : 적립, U : 사용',
	SAV_AMT bigint DEFAULT 0 COMMENT '적립량 : 적립량',
	USE_AMT bigint DEFAULT 0 COMMENT '사용량 : 사용량( 해당 점포에서 고객이 사용한 양 - 집계 )',
	ACCUM_AMT bigint DEFAULT 0 COMMENT '누적량 : 방문 시점 누적량',
	GOOS_NM varchar(512) COMMENT '적용 상품명',
	RMKS varchar(512) COMMENT '비고 : 비고',
	REG_PGM_ID varchar(256) NOT NULL COMMENT '등록프로그램아이디',
	REG_USR_ID varchar(50) COMMENT '등록사용자아이디',
	REG_USR_IP varchar(64) NOT NULL COMMENT '등록사용자아이피',
	REG_DTTM datetime NOT NULL COMMENT '등록일시',
	UPD_PGM_ID varchar(256) NOT NULL COMMENT '수정프로그램아이디',
	UPD_USR_ID varchar(50) COMMENT '수정사용자아이디',
	UPD_USR_IP varchar(64) NOT NULL COMMENT '수정사용자아이피',
	UPD_DTTM datetime NOT NULL COMMENT '수정일시',
	PRIMARY KEY (CH_VISIT_SEQ)
);

CREATE TABLE CM_NATI_CD COMMENT '국가코드'
(
	CM_NATI_CD_SEQ bigint NOT NULL COMMENT '순번 : 고유 식별 값' UNIQUE,
	NATI_CD varchar(2) NOT NULL COMMENT '국가코드',
	NATI_NM_KOR varchar(64) NOT NULL COMMENT '국가코드_한국어',
	NATI_NM_ENG varchar(256) NOT NULL COMMENT '국가코드_영어',
	REG_PGM_ID varchar(256) NOT NULL COMMENT '등록프로그램아이디',
	REG_USR_ID varchar(50) COMMENT '등록사용자아이디',
	REG_USR_IP varchar(64) NOT NULL COMMENT '등록사용자아이피',
	RMKS varchar(512) COMMENT '비고 : 비고',
	REG_DTTM datetime NOT NULL COMMENT '등록일시',
	UPD_PGM_ID varchar(256) NOT NULL COMMENT '수정프로그램아이디',
	UPD_USR_ID varchar(50) COMMENT '수정사용자아이디',
	UPD_USR_IP varchar(64) NOT NULL COMMENT '수정사용자아이피',
	UPD_DTTM datetime NOT NULL COMMENT '수정일시',
	PRIMARY KEY (CM_NATI_CD_SEQ)
);

/* ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
Create Foreign keys
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ */
ALTER TABLE CM_GOOS
	ADD CONSTRAINT FK_CM_STOR_CM_GOOS FOREIGN KEY (CM_STOR_SEQ)
	REFERENCES CM_STOR (CM_STOR_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE CR_USR_STOR
	ADD CONSTRAINT FK_CM_USR_CM_STOR_USR FOREIGN KEY (CM_USR_SEQ)
	REFERENCES CM_USR (CM_USR_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;
ALTER TABLE CR_USR_STOR
	ADD CONSTRAINT FK_CM_STOR_CM_USR_STOR FOREIGN KEY (CM_STOR_SEQ)
	REFERENCES CM_STOR (CM_STOR_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CH_VISIT
	ADD CONSTRAINT FK_CM_USR_CH_VISIT FOREIGN KEY (CM_USR_SEQ)
	REFERENCES CM_USR (CM_USR_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;
ALTER TABLE CH_VISIT
	ADD CONSTRAINT FK_CM_STOR_CH_VISIT FOREIGN KEY (CM_STOR_SEQ)
	REFERENCES CM_STOR (CM_STOR_SEQ)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

/* ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
Create Indexes
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ */
-- 사용자 아이디와 국적코드 Unique 인덱스
CREATE UNIQUE INDEX UK_CM_USR_USR_ID_NATI_CD ON CM_USR (USR_ID, NATI_CD);

-- 사용자명으로　검색
CREATE INDEX IX_CM_USR_USR_NM ON CM_USR (USR_NM);

-- 점포 아이디와 국적코드 Unique 인덱스
CREATE UNIQUE INDEX UK_CM_STOR_STOR_ID_NATI_CD ON CM_STOR (STOR_ID, NATI_CD);

-- 점포명으로　검색
CREATE INDEX IX_CM_STOR_STOR_NM ON CM_STOR (STOR_NM);

-- 국가코드 Unique 인덱스
CREATE UNIQUE INDEX UK_CM_NATI_CD_ID ON CM_NATI_CD (NATI_CD);

/* ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
Test data insert( Not essential )
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ */
/*
INSERT INTO CM_USR( CM_USR_SEQ, USR_ID, USR_TP, PASSWD, USR_NM, NATI_CD, MARKET_AGREE_YN, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM )
VALUES( SQ_CM_USR.NEXTVAL, 'TEST1', 'U', 'QQQQQQQQQ', '이재성', 'KOR', 'N', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );

INSERT INTO CM_STOR( CM_STOR_SEQ, STOR_ID, STOR_NM, SAV_TP, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM )
VALUES( SQ_CM_STOR.NEXTVAL, 'TEST1', 'TEST점포', 'C', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
*/


/* Refer : https://eminwon.qia.go.kr/common/CountrySP.jsp */
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'AD', '안도라', 'ANDORRA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'AE', '아랍에미리트', 'UNITED ARAB EMIRATES', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'AF', '아프가니스탄', 'AFGHANISTAN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'AG', '안티구아 바부다', 'ANTIGUA AND BARBUDA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'AI', '앙길라', 'ANGUILLA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'AL', '알바니아', 'ALBANIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'AM', '아르메니아', 'ARMENIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'AN', '네덜란드령 안틸레스', 'NETHERLANDS ANTILLES', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'AO', '앙골라', 'ANGOLA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'AQ', '안타티카', 'ANTARCTICA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'AR', '아르헨티나', 'ARGENTINA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'AS', '아메리칸 사모아', 'AMERICAN SAMOA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'AT', '오스트리아', 'AUSTRIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'AU', '호주', 'AUSTRALIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'AW', '아루바', 'ARUBA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'AX', '알랜드 군도', 'ALAND ISLANDS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'AZ', '아제르바이잔', 'AZERBAIJAN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BA', '보스니아 헤르체고비나', 'BOSNIA HERCEGOVINA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BB', '바베이도스', 'BARBADOS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BD', '방글라데시', 'BANGLADESH', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BE', '벨기에', 'BELGIUM', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BF', '부르키나파소', 'BURKINA FASO', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BG', '불가리아', 'BULGARIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BH', '바레인', 'BAHRAIN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BI', '브룬디', 'BURUNDI', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BJ', '베냉', 'BENIN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BL', '세인트 바르탤르미', 'SAINT BARTHELEMY', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BM', '버뮤다', 'BERMUDA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BN', '브루나이', 'BRUNEI DARUSSALAM', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BO', '볼리비아', 'BOLIVIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BQ', '보네르', 'BONAIRE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BR', '브라질', 'BRAZIL', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BS', '바하마', 'BAHAMAS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BT', '부탄', 'BHUTAN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BV', '부베섬', 'BOUVET ISLAND', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BW', '보츠와나', 'BOTSWANA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BY', '벨라루스', 'BELARUS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'BZ', '벨리즈', 'BELIZE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'CA', '캐나다', 'CANADA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'CC', '코코스 제도', 'COCOS (KEELING) ISLANDS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'CD', '콩고민주공화국', 'Democratic Republic of the Congo', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'CF', '중앙아프리카공화국', 'CENTRAL AFRICAN REPUBLIC', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'CG', '콩고', 'CONGO', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'CH', '스위스', 'SWITZERLAND', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'CI', '코트디부아르', 'COTE D`IVOIRE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'CK', '쿡 제도', 'COOK ISLANDS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'CL', '칠레', 'CHILE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'CM', '카메룬', 'CAMEROON', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'CN', '중국', 'CHINA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'CO', '콜롬비아', 'COLOMBIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'CR', '코스타리카', 'COSTA RICA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'CU', '쿠바', 'CUBA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'CV', '카보베르데', 'CAPE VERDE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'CW', '큐라소', 'CURACAO', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'CX', '크리스마스섬', 'CHRISTMAS ISLAND', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'CY', '사이프러스', 'CYPRUS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'CZ', '체코공화국', 'CZECH REPUBLIC', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'DE', '독일', 'GERMANY', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'DJ', '지부티', 'DJIBOUTI', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'DK', '덴마크', 'DENMARK', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'DM', '도미니카', 'DOMINICA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'DO', '도미니카 공화국', 'DOMINICAN REPUBLIC', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'DZ', '알제리', 'ALGERIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'EC', '에쿠아도르', 'ECUADOR', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'EE', '에스토니아', 'ESTONIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'EG', '이집트', 'EGYPT', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'EH', '서사하라', 'WESTERN SAHARA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'ER', '에리트레아', 'ERITREA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'ES', '스페인', 'SPAIN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'ET', '이디오피아', 'ETHIOPIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'FI', '핀란드', 'FINLAND', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'FJ', '피지', 'FIJI', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'FK', '포클랜드섬', 'FALKLAND ISLANDS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'FM', '미크로네시아', 'MICRONESIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'FO', '페로 군도', 'FAROE ISLANDS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'FR', '프랑스', 'FRANCE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'GA', '가봉', 'GABON', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'GB', '영국', 'UNITED KINGDOM', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'GD', '그레나다', 'GRENADA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'GE', '구루지아', 'GEORGIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'GF', '프랑스령 기아나', 'FRENCH GUIANA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'GG', '건지', 'GUERNSEY', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'GH', '가나', 'GHANA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'GI', '지브랄타', 'GIBRALTAR', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'GL', '그린랜드', 'GREENLAND', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'GM', '감비아', 'GAMBIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'GN', '기니', 'GUINEA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'GP', '과들루프', 'GUADELOUPE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'GQ', '적도 기니', 'EQUATORIAL GUINEA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'GR', '그리스', 'GREECE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'GS', '사우스조지아 사우스샌드위치 제도', 'SOUTH GEORGIA AND SOUTH SANDWICH LSLANDS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'GT', '과테말라', 'GUATEMALA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'GU', '괌', 'GUAM', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'GW', '기네비쏘', 'GUINEA-BISSAU', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'GY', '가이아나', 'GUYANA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'HK', '홍콩', 'HONG KONG', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'HM', '허드 맥도날드 군도', 'HEARD AND MCDONALD ISLANDS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'HN', '온두라스', 'HONDURAS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'HR', '크로아티아', 'CROATIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'HT', '아이티', 'HAITI', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'HU', '헝가리', 'HUNGARY', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'ID', '인도네시아', 'INDONESIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'IE', '아일랜드', 'IRELAND', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'IL', '이스라엘', 'ISRAEL', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'IM', '맨섬', 'ISLE OF MAN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'IN', '인도', 'INDIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'IO', '영인도 제도', 'BRITISH INDIAN OCEAN TERRITORY', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'IQ', '이라크', 'IRAQ', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'IR', '이란', 'IRAN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'IS', '아이슬랜드', 'ICELAND', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'IT', '이탈리아', 'ITALY', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'JE', '저지', 'JERSEY', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'JM', '자메이카', 'JAMAICA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'JO', '요르단', 'JORDAN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'JP', '일본', 'JAPAN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'KE', '케냐', 'KENYA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'KG', '키르기스스탄', 'KYRGYZSTAN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'KH', '캄보디아', 'CAMBODIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'KI', '키리바시', 'KIRIBATI', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'KM', '코모르', 'COMOROS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'KN', '세인트 키츠 네비스', 'SAINT KITTS AND NEVIS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'KP', '북한', 'NORTH KOREA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'KR', '대한민국', 'KOREA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'KV', '코소보', 'KOSOVO', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'KW', '쿠웨이트', 'KUWAIT', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'KY', '케이맨섬', 'CAYMAN ISLANDS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'KZ', '카자흐스탄', 'KAZAKHSTAN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'LA', '라오스', 'LAOS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'LB', '레바논', 'LEBANON', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'LC', '세인트 루시아', 'SAINT LUCIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'LI', '리히텐슈타인', 'LIECHTENSTEIN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'LK', '스리랑카', 'SRI LANKA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'LR', '라이베리아', 'LIBERIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'LS', '레소토', 'LESOTHO', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'LT', '리투아니아', 'LITHUANIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'LU', '룩셈부르크', 'LUXEMBOURG', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'LV', '라트비아', 'LATVIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'LY', '리비아', 'LIBYAN ARAB JAMAHIRIYA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MA', '모로코', 'MOROCCO', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MC', '모나코', 'MONACO', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MD', '몰도바', 'MOLDOVA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'ME', '몬테네그로', 'MONTENEGRO', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MF', '세인트 마틴', 'SAINT MARTIN (FRENCH PART)', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MG', '마다가스카르', 'MADAGASCAR', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MH', '마샬군도', 'MARSHALL ISLANDS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MK', '마케도니아', 'MACEDONIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'ML', '말리', 'MALI', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MM', '미얀마', 'MYANMAR', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MN', '몽골', 'MONGOLIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MO', '마카오', 'MACAU', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MP', '북마리아나 군도', 'NORTHERN MARIANA ISLANDS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MQ', '마르티니크', 'MARTINIQUE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MR', '모리타니', 'MAURITANIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MS', '몬트세라트', 'MONTSERRAT', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MT', '말타', 'MALTA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MU', '모리셔스', 'MAURITIUS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MV', '몰디브', 'MALDIVES', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MW', '말라위', 'MALAWI', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MX', '멕시코', 'MEXICO', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MY', '말레이지아', 'MALAYSIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'MZ', '모잠비크', 'MOZAMBIQUE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'NA', '나미비아', 'NAMIBIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'NC', '뉴칼레도니아', 'NEW CALEDONIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'NE', '니제르', 'NIGER', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'NF', '노퍽섬', 'NORFOLK ISLAND', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'NG', '나이지리아', 'NIGERIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'NI', '니카라과', 'NICARAGUA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'NL', '네덜란드', 'NETHERLANDS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'NO', '노르웨이', 'NORWAY', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'NP', '네팔', 'NEPAL', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'NR', '나우루', 'NAURU', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'NT', '중립지대', 'NEUTRAL ZONE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'NU', '니우에', 'NIUE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'NZ', '뉴질랜드', 'NEW ZEALAND', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'OM', '오만', 'OMAN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'PA', '파나마', 'PANAMA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'PE', '페루', 'PERU', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'PF', '프랑스령 폴리네시아', 'FRENCH POLYNESIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'PG', '파푸아뉴기니', 'PAPUA NEW GUINEA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'PH', '필리핀', 'PHILIPPINES', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'PK', '파키스탄', 'PAKISTAN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'PL', '폴란드', 'POLAND', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'PM', '세인트 피에르 미?론', 'SAINT PIERRE AND MIQUELON', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'PN', '핏케언 군도', 'PITCAIRN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'PR', '푸에르토리코', 'PUERTO RICO', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'PS', '팔레스타인', 'PALESTINE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'PT', '포르투갈', 'PORTUGAL', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'PW', '팔라우', 'PALAU', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'PY', '파라과이', 'PARAGUAY', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'QA', '카타르', 'QATAR', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'RE', '리유니언', 'REUNION', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'RO', '루마니아', 'ROMANIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'RS', '세르비아', 'SERBIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'RU', '러시아', 'RUSSIAN FEDERATION', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'RW', '르완다', 'RWANDA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'SA', '사우디아라비아', 'SAUDI ARABIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'SB', '솔로몬 군도', 'SOLOMON ISLANDS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'SC', '세이셸', 'SEYCHELLES', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'SD', '수단', 'SUDAN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'SE', '스웨덴', 'SWEDEN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'SG', '싱가포르', 'SINGAPORE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'SH', '세인트 헬레나', 'SAINT HELENA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'SI', '슬로베니아', 'SLOVENIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'SJ', '스발바르드 얀마이엔 제도', 'SVALBARD AND JAN MAYEN ISLANDS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'SK', '슬로바키아', 'SLOVAKIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'SL', '시에라리온', 'SIERRA LEONE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'SM', '산마리노', 'SAN MARINO', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'SN', '세네갈', 'SENEGAL', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'SO', '소말리아', 'SOMALIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'SR', '수리남', 'SURINAME', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'SS', '남수단', 'SOUTH SUDAN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'ST', '쌍투메 프린시페', 'SAO TOME AND PRINCIPE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'SV', '엘살바도르', 'EL SALVADOR', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'SX', '신트마르텐', 'SINT MAARTEN (DUTCH PART)', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'SY', '시리아', 'SYRIAN ARAB REPUBLIC', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'SZ', '스와질랜드', 'SWAZILAND', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'TC', '터크스 카이코스 제도', 'TURKS AND CAICOS ISLANDS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'TD', '차드', 'CHAD', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'TF', '프랑스 남부지역', 'FRENCH SOUTHERN TERRITORIES', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'TG', '토고', 'TOGO', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'TH', '태국', 'THAILAND', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'TJ', '타지키스탄', 'TAJIKISTAN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'TK', '토켈라우', 'TOKELAU', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'TL', '동티모르', 'EAST TIMOR', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'TM', '투르크메니스탄', 'TURKMENISTAN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'TN', '튀니지', 'TUNISIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'TO', '통가', 'TONGA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'TR', '터키', 'TURKEY', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'TT', '트리니다드토바고', 'TRINIDAD AND TOBAGO', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'TV', '투발루', 'TUVALU', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'TW', '대만', 'TAIWAN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'TZ', '탄자니아', 'TANZANIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'UA', '우크라이나', 'UKRAINE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'UG', '우간다', 'UGANDA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'UM', '미국령 소군도', 'UNITED STATES MINOR OUTLYING ISLANDS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'US', '미국', 'UNITED STATES', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'UY', '우루과이', 'URUGUAY', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'UZ', '우즈베키스탄', 'UZBEKISTAN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'VA', '바티칸', 'VATICAN CITY STATE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'VC', '세인트 빈센트 그레나딘스', 'SAINT VINCENT AND THE GRENADINES', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'VE', '베네수엘라', 'VENEZUELA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'VG', '영국령 버진아일랜드', 'VIRGIN ISLANDS (BRITISH)', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'VI', '미국령 버진아일랜드', 'VIRGIN ISLANDS (U.S.)', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'VN', '베트남', 'VIET NAM', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'VU', '바누아투', 'VANUATU', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'WF', '월리스 후트나', 'WALLIS AND FUTUNA ISLANDS', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'WS', '사모아', 'SAMOA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'YE', '예멘', 'YEMEN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'YT', '마요트', 'MAYOTTE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'YU', '유고슬라비아', 'YUGOSLAVIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'ZA', '남아프리카공화국', 'SOUTH AFRICA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'ZM', '잠비아', 'ZAMBIA', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'ZR', '자이르', 'ZAIRE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'ZW', '짐바브웨', 'ZIMBABWE', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );
INSERT INTO CM_NATI_CD( CM_NATI_CD_SEQ, NATI_CD, NATI_NM_KOR, NATI_NM_ENG, REG_PGM_ID, REG_USR_IP, REG_DTTM, UPD_PGM_ID, UPD_USR_IP, UPD_DTTM ) VALUES( SQ_CM_NATI_CD.NEXTVAL, 'ZZ', '국적불명', 'UNKNOWN', 'MANUAL', '127.0.0.1', SYSDATE, 'MANUAL', '127.0.0.1', SYSDATE );

COMMIT;